# This configuration file allows you to configure the back-end side of things
# The configuration file's location should be passed as the first argument when launching EpiLink

# The name of the server. You can customize this if you want to.
name: My EpiLink Instance

# HTTP server configuration
server:
  # The port that should be used for the server.
  port: 9090
  # Time in milliseconds before a session expires. Here, one month
  sessionDuration: 2592000000
  # The URL of the front-end, WITH a trailing slash /, or null if the URL is unknown
  # Leave as ~ if the front-end is bootstrapped (i.e. the front-end is served on the same server as the back-end)
  frontendUrl: ~

# Name and location of the EpiLink SQLite database
db: epilink.db

# The tokens to use when connecting
# Note that providing them in the configuration file is optional. If you do not define them here, you can pass them as
# environment values.
tokens:
  # The application JWT tokens' signature's secret key
  jwtSecret: I am a secret ! Please change me :(
  # The token for the Discord bot
  discordToken: ~
  # The client ID for Discord's OAuth2
  discordOAuthClientId: ~
  # The secret for Discord's OAuth2
  discordOAuthSecret: ~
  # The client ID for Microsoft's OAuth2
  msftOAuthClientId: ~
  # The secret for Microsoft's OAuth2
  msftOAuthSecret: ~
  # The tenant for Microsoft OAuth requests.
  # This can be "common" (allow everyone) or an ID specific to a company/school.
  msftTenant: common
