name: Build and test

on:
  push:
    branches: [dev, master]
  pull_request:

jobs:
  license:
    name: License headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check license headers
        run: ./gradlew license

  backend-tests:
    name: Build and test back-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew jar
      - name: Test with gradle
        run: ./gradlew check
      - name: Create and upload code coverage report
        run: |
          ./gradlew jacocoTestReport
          bash <(curl -s https://codecov.io/bash) -f bot/build/reports/jacoco/test/jacocoTestReport.xml
      - name: Upload tests failure report to artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test-failure-report
          path: bot/build/reports/tests/test

  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate documentation
        run: ./gradlew generateDocs

  frontend-build:
    name: Build front-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile front-end JAR
        run: ./gradlew frontJar -PwithFrontend

  full-dist-build:
    needs: [license, backend-tests, frontend-build, docs]
    name: Full distribution build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build frontend-less dist
        run: ./gradlew assembleDist
      - name: Build dist with bundled front-end
        run: ./gradlew assembleDist -PwithFrontend
      - uses: actions/upload-artifact@v2
        with:
          path: |
            bot/build/distributions/epilink-backend-*.zip
            bot/build/distributions/epilink-backend-*.tar

