name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check license headers
        run: ./gradlew license
      - name: Build with Gradle
        run: ./gradlew jar
      - name: Test with gradle
        run: ./gradlew check
      - name: Upload tests failure report to artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test-failure-report
          path: bot/build/reports/tests/test